apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-2048
  namespace: argo-cd
spec:
  project: default

  source:
    repoURL: "https://github.com/hanimao/eks-project"
    targetRevision: main
    path: manifests

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: game-2048

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true